spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://161.35.231.114:3306/UsedCarSalesDemo?useUnicode=true&characterEncoding=utf-8
    password: c7c55d02-46ae-4c9d-9d56-df3c9c3cf607
    username: usedcarsales
    jpa:
      hibernate:
        ddl-auto: none